config/routes.rb
Bigbrother::Application.routes.draw do

  match '/auth/:provider/callback' => 'sessions#create' # omniauth
  
  get 'logout' => 'sessions#destroy', :as => "logout"
  get 'login' => 'sessions#index', :as => "login"

  get 'me' => 'users#me', as: "me"
  put 'me/update_preferences' => 'users#update_preferences', as: 'update_my_preferences'

  resources :sessions

  resources :preguntas do
    member do
      post :vote
      post :share
    end
    collection do
      get :me
    end
  end

  get '/faqs' => 'faqs#index', :as => "faqs"

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'preguntas#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  match '*a', :to => 'application#routing_error'
end

app/models/pregunta.rb
# encoding: utf-8
class Pregunta < ActiveRecord::Base
  attr_accessible :titulo,
                  :detalle,
                  :enlace,
                  :dirigida_a

  attr_accessor :dirigida_a

  # relationships:
    belongs_to :user
    belongs_to :member
    has_reputation :votes,
                   source: :user,
                   source_of: [{ reputation: :user_votes, of: :user }],
                   aggregated_by: :sum

  # validations:
    validates :titulo, :presence => true
    validates :detalle, :presence => true
    # validates :dirigida_a, :presence => true
    validates :user_id, :presence => true
    validates :member_id, :presence => true
    validate :dirigida_a_has_one_valid_member

  # class methods:
    def self.candidatos_nombres
      Member.candidatos_with_lista
    end
    #def self.get_message_to_share
    #  messages = [
    #    "Recomiendo la pregunta"
    #  ]
    #  messages[(rand*messages.length).to_i]
    #end

  # instance methods:
    def dirigida_a=( name_with_lista )
      if name_with_lista.include? "("
        name_with_lista.slice!( (name_with_lista.index("(") - 1), (name_with_lista.length - name_with_lista.index("(") + 1) )
      end
      logger.debug "name: \n#{name_with_lista}"
      self.member = Member.find_by_nombre name_with_lista
    end
    def dirigida_a
      self.member.candidato_with_lista if self.member
    end
    

  private

    def dirigida_a_has_one_valid_member
      unless Member.exists?(id: self.member_id)
        errors.add :dirigida_a, "candidato no válido"
      end
    end

end

app/controllers/preguntas_controller.rb
# encoding: utf-8
class PreguntasController < ApplicationController
  
  before_filter :confirm_logged_in, :only => :me

  def index
    if session[:has_asked_question]
      begin
        @pregunta = Pregunta.new JSON.parse(session[:has_asked_question])
      rescue 
        @pregunta = Pregunta.new
      end
      @place = "preguntas_new"
      @auto_submit_form = true
      session[:has_asked_question] = nil
      render :new
    else
      @preguntas_pag = Pregunta.page(params[:page]).per(10)
      @preguntas = @preguntas_pag.includes(:user, :member).find_with_reputation(:votes, :all, order: "votes desc")
      @place = "preguntas_index"
    end
  end

  def new
    @place = "preguntas_new"
    if session[:has_asked_question]
      @pregunta ||= Pregunta.new JSON.parse(session[:has_asked_question])
    else
      @pregunta ||= Pregunta.new
    end
  end

  def create
    if current_user
      @pregunta = Pregunta.new params[:pregunta]
      @pregunta.user = current_user
      if @pregunta.save
        flash["alert-success"] = "acabas de preguntar."
        link = "#{request.protocol}#{request.host_with_port}/preguntas/#{@pregunta.id}"
        if @pregunta.member.nombre == "Todos"
          message_candidato = "a todos los candidatos"
        else
          message_candidato = "al candidato #{@pregunta.member.nombre_or_nickname}"
        end
        current_user.share_to_social_networks({
          :message => "#EleccionesEC Acabo de colocar una pregunta #{message_candidato}. #{link}",
          :link => link
        })
        redirect_to action: :index
      else
        flash["alert-error"] = "hubo un problema al guardar tu pregunta. Asegúrate de haber llenado los campos requeridos."
        @place = "preguntas_new"
        render :new
      end
    else
      flash["alert-info"] = "por favor, inicia sesión para que tu pregunta sea válida"
      session[:has_asked_question] = params[:pregunta].to_json
      redirect_to login_url
    end
  end
  
  def show
    @pregunta = Pregunta.find(params[:id], include: :user)
    case Pregunta.count
    when 1..4
      limit = 1
    else
      limit = 2
    end
    no_populares = Pregunta.includes(:user).find_with_reputation(:votes, :all, order: "votes asc, id desc", limit: (limit+1))
    populares = Pregunta.includes(:user).find_with_reputation(:votes, :all, order: "votes desc, id desc", limit: limit)
    @preguntas = no_populares.zip(populares).flatten.compact
  end
  
  def vote
    if current_user
      if @pregunta = Pregunta.find_by_id(params[:id])
        if @pregunta.has_evaluation? :votes, current_user
          @pregunta.delete_evaluation(:votes, current_user)
        else
          if current_user.reputation_for(:user_votes).to_i >= current_user.allowed_votes_count
            flash["alert-error"] = "puedes votar hasta por #{current_user.allowed_votes_count} preguntas. Recuerda que mientras más preguntas coloques, por más preguntas puedes votar."
            @error = true
            return
          end
          @pregunta.add_or_update_evaluation(:votes, 1, current_user)
        end
      end
    end
    respond_to do |format|
      format.html do
        redirect_to :back 
      end
      format.js do
        render 'vote'
      end
    end
  end
  
  def share
    if current_user
      @pregunta = Pregunta.find params[:id], :include => [:user, :member]
      link = "#{request.protocol}#{request.host_with_port}/preguntas/#{@pregunta.id}"
      if @pregunta.member.nombre == "Todos"
        message_for_candidato = "a todos los candidatos"
      else
        message_for_candidato = "al candidato #{@pregunta.member.nombre_or_nickname}"
      end
      obj = {
        :message => "#EleccionesEC me gustó esta pregunta que #{@pregunta.user.twitter_or_fb_nickname} hizo #{message_for_candidato}. #{link}",
        :link => link
      }
      current_user.share_to_social_networks(obj)
      flash["alert-success"] = "Lo hemos compartido con tus amigos."
    else
      flash["alert-error"] = "Inicia sesión antes de poder compartir."
    end
    respond_to do |format|
      format.html do 
        if current_user
          redirect_to :back
        else
          redirect_to login_url
        end
      end
      format.js
    end
  end
  
  def me
    @place = "mis_preguntas"
    @preguntas_pag = current_user.preguntas.page(params[:page]).per(10)
    @preguntas = @preguntas_pag.includes(:user, :member).find_with_reputation(:votes, :all, order: "votes desc")
  end

end

app/helpers/preguntas_helper.rb
module PreguntasHelper
end

app/views/preguntas/_pregunta.html.erb
<% 
  unless defined? current 
    current = false
  end
%>

<div class="pregunta row-fluid pregunta_<%= pregunta.id %>">
  <div class="user span2">
    <%= image_tag pregunta.user.image, :class => "profile_picture" %>
    <div class="screen_name">
      <%= raw pregunta.user.link_to_default_profile %>
    </div>
    <div class="user_name">
      <%= raw pregunta.user.name %>
    </div>
  </div>
  <div class="details span9">
    <div class="title">
      <%= pregunta.titulo %>
    </div>
    <div class="desc">
      <%= pregunta.detalle %>
    </div>
    <div class="pregunta_link">
      <%= pregunta.enlace %>
    </div>
    <div class="time_ago">
      Pregunta a <%= pregunta.dirigida_a %>
    </div>
    <div class="time_ago">
      hace <%= time_ago_in_words pregunta.created_at %>
    </div>
		<div class="reputation">
      <%= render 'pregunta_reputation', pregunta: pregunta, current: current %>
		</div>
  </div>
</div>

app/views/preguntas/_pregunta_reputation.html.erb
<%
if current_user
  if pregunta.has_evaluation? :votes, current_user
    status = 'fav_star'
  else
    status = 'white_star'
  end
else
  status = 'white_star'
end
unless defined? current
  current = false
end
%>
<%= link_to vote_pregunta_path(pregunta), method: "post", class: "star", remote: true do %><span class='<%= status %>'></span><% end %>
<span class='votes_total'>
  (<%= pregunta.reputation_for(:votes).to_i %>)
</span>

<div class="share_pregunta">
  <%= link_to raw("<i class='icon-share'></i>"), share_pregunta_path(pregunta), method: "post", remote: true, class: "ttip", rel: "tooltip", title: "Recomendar", data: { placement: "right" } %>
</div>

<% unless current %> 
  <div class="show_pregunta">
    <%= link_to raw("<i class='icon-zoom-in'></i>"), pregunta_path(pregunta), class: "ttip", rel: "tooltip", title: "Ver detalles", data: { placement: "right" } %>
  </div>
<% end %>

app/views/preguntas/index.html.erb
<div class="all_preguntas container-fluid">
  <% if @preguntas.length == 0 %>
    <div class="has_padding">
      <h3>Aún no hay preguntas</h3>
      <p>¡Sé el primero en <%= link_to "preguntar", new_pregunta_path %>!</p>
    </div>
  <% else %>
    <% @preguntas.each do |pregunta| %>
      <%= render 'pregunta', pregunta: pregunta %>
    <% end %>
  <% end %>
</div>

<%= paginate @preguntas_pag %>

app/views/preguntas/me.html.erb
<div class="all_preguntas container-fluid">
  <% if @preguntas.length == 0 %>
    <div class="has_padding">
      <h3>Aún no has preguntado</h3>
      <p><%= link_to "Preguntar", new_pregunta_path %></p>
    </div>
  <% else %>
    <% @preguntas.each do |pregunta| %>
      <%= render 'pregunta', pregunta: pregunta %>
    <% end %>
  <% end %>
</div>

<%= paginate @preguntas_pag %>

app/views/preguntas/new.html.erb
<div class="pregunta_new">

  <div class="pregunta_new_title">
    <h2>Nueva pregunta</h2>
  </div>

  <%= form_for @pregunta, :url => preguntas_path, :html => {:class => "is_form_horizontal"} do |f| %>
    <div class="field">
      <%= f.label :titulo, "Título" %>
      <%= f.text_field :titulo, :placeholder => "Título de la pregunta", :required => true %>
    </div>
    <div class="field">
      <%= f.label :detalle, "Detalle" %>
      <%= f.text_area :detalle, :placeholder => "Descripción (contexto) de la pregunta", :required => true %>
    </div>
    <div class="field">
      <%= f.label :enlace, "Enlace" %>
      <%= f.text_field :enlace, :placeholder => "(opcional) enlace que ayude al contexto" %>
    </div>
    <div class="field">
      <%= f.label :dirigida_a, "Dirigida a" %>
      <%= f.select :dirigida_a, Member.candidatos_with_lista %>
    </div>
    <div class="field">
      <%= f.submit "Preguntar", :disable_with => 'Enviando..', :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

<% if @auto_submit_form %>
  <%= javascript_tag do %>
    $(function(){
      $("form.is_form_horizontal").submit();
    });
  <% end %>
<% end %>

app/views/preguntas/share.js.erb
<%= js_send_all_notifications %>
<% unless current_user %>
  window.location = '/login';
<% end %>

app/views/preguntas/show.html.erb
<div class="all_preguntas container-fluid">
  <div class="active_pregunta">
    <%= render 'pregunta', pregunta: @pregunta, current: true %>
    <% if @pregunta.evaluations.count > 0 %>
      <div class="active_pregunta_details">
        <h4>Le ha gustado a:</h4>
        <% @pregunta.evaluations.includes(:source).each do |evaluation| %>
          <%= link_to evaluation.source.default_profile_link, :class => "user_has_liked ttip nolink", :rel => "tooltip", :title => evaluation.source.default_profile_display, "data-placement" => "bottom", :target => "blank" do %>
            <%= image_tag evaluation.source.image %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="has_padding">
  
</div>

<h3>Otras preguntas</h3>
<div class="all_preguntas container-fluid">
  <% @preguntas.each do |pregunta| %>
    <%= render 'pregunta', pregunta: pregunta %>
  <% end %>
</div>

app/views/preguntas/vote.js.erb
<% if current_user %>
  <% unless @error %>
    $(".all_preguntas .pregunta_<%= @pregunta.id %> .details .reputation").html("<%= j(render('preguntas/pregunta_reputation', pregunta: @pregunta)) %>");
    window.Helpers.Tooltip.init();
  <% end %>
<% else %>
  window.location = "/login";
<% end %>
<%= js_send_all_notifications %>