config/routes.rb
Bigbrother::Application.routes.draw do

  match '/auth/:provider/callback' => 'sessions#create' # omniauth
  
  get 'logout' => 'sessions#destroy', :as => "logout"
  get 'login' => 'sessions#index', :as => "login"

  get 'me' => 'users#me', as: "me"
  put 'me/update_preferences' => 'users#update_preferences', as: 'update_my_preferences'

  resources :sessions

  resources :preguntas do
    member do
      post :vote
      post :share
    end
    collection do
      get :me
    end
  end

  get '/faqs' => 'faqs#index', :as => "faqs"

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'preguntas#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  match '*a', :to => 'application#routing_error'
end

app/views/layouts/_curtains.html.erb
<h2>
  el 17 de febrero empezaremos a preparar conversaciones...
</h2>

<%= image_tag "/images/curtains.png", :id => "curtains_img" %>

<h3>...condimenta tu conversación, cocínala, pídela para llevar y sírvetela,<br />
  ...te invitamos a unirte a este <span class="default_red">q</span>oloquio.</h3>

<div class="align_center">
  <%= link_to "http://facebook.com/qoloquio", :target => "_blank" do image_tag("/images/fblogo.png", :class => "social_network_logo ttip", :title => "/qoloquio", :data => {:placement => "bottom"}) end %>
  <%= link_to "http://twitter.com/intent/user?screen_name=qoloquio", :target => "_blank" do image_tag("/images/twitterbird.png", :class => "social_network_logo ttip", :title => "@qoloquio", :data => {:placement => "bottom"}) end %>
  <%= link_to "skype:qoloquio?call" do image_tag("/images/SkypeBlue.png", :class => "social_network_logo ttip", :title => "qoloquio", :data => {:placement => "bottom"}) end %>
</div>

<div class="divisory_line_curtains"></div>

<div class="align_center">
	<h3>retransmiten en simultáneo:</h3>
	<a href="http://lahora.com.ec/" target="_blank"><img src="/images/logo_la_hora.jpg" class="sponsors_logos_small"></a>
	<a href="http://kocodriloradio.com/" target="_blank"><img src="/images/logo_kocodrilo.jpg" class="sponsors_logos_small" style="max-width: 160px;"></a>
	<a href="http://www.13plus.com.ec/" target=_blank><img src="/images/logo_13plus.png" class="sponsors_logos_small" style=""></a>
</div>

<div class="divisory_line_curtains"></div>

<video width="640" height="360" controls preload="none" poster="/images/video_poster.png">
  <source src="http://qoloquio.com.s3.amazonaws.com/eleccionesec/video/promo2_720.mov" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
  <source src="http://qoloquio.com.s3.amazonaws.com/eleccionesec/video/promo2.ogg" type='video/ogg; codecs="theora, vorbis"'>
  Por favor actualiza tu navegador.
</video>

<div class="divisory_line_curtains"></div>

app/views/layouts/_notifications.html.erb
<div id="notifications" class="alerts">
  <% flash.each do |key, msg| %>
    <div class="alert <%= key.to_s %>">
      <a class="close" data-dismiss="alert" href="#">x</a>
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/_sidebar.html.erb
<ul class="nav nav-list">
  <li class="nav-header">
    preguntas
  </li>
  <li <%= active? "preguntas_index" %>>
    <%= link_to "todas", preguntas_path %>
  </li>
  <li <%= active? "faqs" %>>
    <%= link_to "preguntas frecuentes", faqs_path %>
  </li>
  <li <%= active? "preguntas_new" %>>
    <%= link_to "nueva", new_pregunta_path %>
  </li>
  <% if current_user %>
  <li <%= active? "mis_preguntas" %>>
    <%= link_to "mis preguntas", me_preguntas_path %>
  </li>
  <% end %>
  <li class="divider"></li>
  <% if current_user %>
    <!-- <li <%= active? "mis_preferencias" %>>
      <%= link_to "mis preferencias", me_path %>
    </li> -->
    <li>
      <%= link_to "cerrar sesión", logout_url %>
    </li>
  <% else %>
    <li <%= active? "iniciar_sesion" %>>
      <%= link_to "iniciar sesión", login_url %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link rel="author" href="/humans.txt">
  <title>qoloquio &raquo; preguntas</title>
  <meta name="description" content="">
  <meta name="author" content="Mario Andrés Correa">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!--[if lt IE 9]><p class=chromeframe>Tu navegador está <strong>obsoleto</strong>. <a href="http://browsehappy.com/">Actualiza a un navegador diferente</a> o <a href="http://www.google.com/chromeframe/?redirect=true">instala google chrome frame</a> (le dará esteroides a tu navegador actual).</p><![endif]-->
  <header>
    <% if @place == "preguntas_index" %>
      <%= render '/layouts/curtains' %>
    <% else %>
      <div id="qoloquio_logo_and_text">
        <%= image_tag "/images/qoloquio_logo.png", id: "qoloquio_logo" %>
        <div id="qoloquio_title">conversaciones para llevar</div>
      </div>
    <% end %>
  </header>
  <div id="main">
    <div id="main_header">
      <div class="current_user_name">
        <% if current_user %>
          <%= current_user.name %>
          <%= image_tag current_user.image, :class => "profile_picture_mini" %>
        <% else %>
          <%= link_to "inicia sesión", login_url %>
        <% end %>
      </div>
      <%= render 'layouts/notifications' %>
    </div>
    <div id="sidebar">
      <%= render 'layouts/sidebar' %>
    </div>
    <div id="the_content">
      <%= yield %>
    </div>
  </div>
  <footer>
  </footer>
  <div class="has_padding"></div>
</body>
</html>